name: Release Preview

on:
  pull_request:
  workflow_dispatch:

jobs:
  publish-pkg-pr-new:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: aa900031/github-actions/setup-node@main
        with:
          no-turbo-cache: 'true'

      - name: Publish to pkg.pr.new
        run: pnpm dlx pkg-pr-new publish --compact
