name: Release Preview

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  pull_request:
  workflow_dispatch:

jobs:
  publish-pkg-pr-new:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .tool-versions

      - name: Publish to pkg.pr.new
        run: pnpm dlx pkg-pr-new publish
